### ISSUE TITLE
关于训练过程中IoU值和mIoU值不变的情况

### ISSUE THREAD

**Issue by thx13** [RuiZhang97/ISNet#13]
你好，我想问一下我在训练过程出现IoU值从一开始到最后都没有变化，是因为什么问题？还有就是这个网络是否是比较难训练到收敛，我看论文中给出500epoch即可达到收敛，而代码则需要3000

**Comment by RuiZhang97** [comment]
已在邮箱回复

**Comment by Joazs** [comment]
您好，请问代码开源了吗？可以分享给我吗？
邮箱: 992202340@qq.com。
期待您的回复，十分感谢！
