### ISSUE TITLE
paper request

### ISSUE THREAD

**Issue by ChunmineHe0224** [RuiZhang97/ISNet#2]
Can the paper be made public?

**Comment by chaimi2013** [comment]
> 

Thanks for your interest in our work. The public date of this paper is upon IEEE/CVF, please be patient. If you want to get a preprint version, I can send it to you. Please leave an email address.

**Comment by Lg955** [comment]
> > 
> 
> Thanks for your interest in our work. The public date of this paper is upon IEEE/CVF, please be patient. If you want to get a preprint version, I can send it to you. Please leave an email address.

991220907@qq.com  Thank you！

**Comment by chaimi2013** [comment]
> 

done.

**Comment by chaimi2013** [comment]
> > > 
> > 
> > 
> > Thanks for your interest in our work. The public date of this paper is upon IEEE/CVF, please be patient. If you want to get a preprint version, I can send it to you. Please leave an email address.
> 
> [991220907@qq.com](mailto:991220907@qq.com) Thank you！

done.
