### ISSUE TITLE
Edge loss

### ISSUE THREAD

**Issue by q671383789** [RuiZhang97/ISNet#5]
Hey，thanks for ur great work. But I get confused for the edge branch, what's the ground-truth for the edgeloss, is it also the mask picture the same with the main branch's gt?

**Comment by q671383789** [comment]
could u just simply explain how to get it.&nbsp;
I want to repo ur work as soon as possible thx



------------------ Original ------------------
From: Rui Zhang ***@***.***&gt;
Date: Tue,Jun 28,2022 11:05 PM
To: RuiZhang97/ISNet ***@***.***&gt;
Cc: q671383789 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [RuiZhang97/ISNet] Edge loss (Issue #5)





 
The GT of the edge loss is the gradient value of the mask. We will release the code soon.

**Comment by RuiZhang97** [comment]
Of course, for example, for an image, there is a corresponding true value picture, that is, a mask picture. For edge loss, its input is two variables, one is the predicted value of the edge, and the other is the label of the edge, the label of the edge is to perform the gradient operation on the mask image, of course, other methods can be used to make the edge label, such as using the Sobel operator, the Canny operator, etc.

**Comment by q671383789** [comment]
> Of course, for example, for an image, there is a corresponding true value picture, that is, a mask picture. For edge loss, its input is two variables, one is the predicted value of the edge, and the other is the label of the edge, the label of the edge is to perform the gradient operation on the mask image, of course, other methods can be used to make the edge label, such as using the Sobel operator, the Canny operator, etc.

十分感谢，我还是用中文表达一下想问的一个问题吧，就是如果我得到的edge label只包含最外围的一圈pixel为255，其他都为0.这种情况是不是更好，因为直接用sobel应该是得不到这么好的结果的，但是好像在有mask的情况是可以得到这样的图的。
